### ISSUE TITLE
Support removing SSL/TLS from upstream https connection

### ISSUE THREAD

**Issue by felixgr** [mitmproxy/mitmproxy#2329]
I'm trying to use an upstream proxy that expects plain HTTP bytes instead of TLS-encapsulated HTTP for HTTPS URLs. I've tried to modify the scheme and other things but mitmproxy still continues to send a TLS client hello after the initial upstream CONNECT. 

It appears that this is currently unsupported in mitmproxy?

##### Steps to reproduce the problem:

uplink.py:

```
from mitmproxy import ctx

def http_connect(flow):
        flow.request.scheme = 'http'
        flow.request.port = 80
        ctx.log.info('script: connect '+repr(flow))

def request(flow):
        flow.request.scheme = 'http'
        flow.request.port = 80
        ctx.log.info('script: request '+repr(flow))
```

1. socat -v tcp-listen:8082,reuseaddr,fork  TCP:upstreamproxy:999
2. mitmproxy -p 8081 -s uplink.py -U http://localhost:8082 --insecure --no-upstream-cert
3. curl -v -k -x http://127.0.0.1:8081 https://www.google.com

The output of socat is:

```
> 2017/05/11 10:11:56.527763  length=119 from=0 to=118
CONNECT www.google.com:80 HTTP/1.1\r
Host: www.google.com:443\r
User-Agent: curl/7.51.0\r
Proxy-Connection: Keep-Alive\r
\r
< 2017/05/11 10:11:56.720058  length=116 from=0 to=115
HTTP/1.1 200 OK\r
Content-Length: 0\r
Date: Thu, 11 May 2017 08:11:56 GMT\r
Content-Type: text/plain; charset=utf-8\r
\r
> 2017/05/11 10:11:56.753419  length=164 from=119 to=282
............i..RF+,Q..2.=.......
oA5T].Lt....2.,.+.$.#.
.       .0./.(.'.........k.g.9.3.....=.<.5./.....@.\v.......
.......#...\r. ........................................< 2017/05/11 10:11:56.753987  length=82 from=116 to=197
HTTP/1.1 502 Uplink Bad Gateway\r
Content-Length: 131\r
Content-Type: text/plain\r
\r
< 2017/05/11 10:11:56.754159  length=131 from=198 to=328
malformed HTTP request "\\x16\\x03\\x01\\x00\\x9f\\x01\\x00\\x00\\x9b\\x03\\x03\\xd2i\\xe3\\xacRF+,Q\\xa4\\xec2\\xfe=\\x11\\x11\\xf1\\xfe\\xcf\\x0e\\u007f"^C⏎
```

As you can see above, the TLS client hello `\\x16\\x03\\x01\\x00` is sent. The upstream proxy doesn't like it and replies with error 502.

##### Expected behavior

If configured/scripted, mitmproxy should send upstream HTTP bytes for a HTTPS URL.

##### Any other comments? What have you tried so far?

I also tried some variants of uplink.py, also the script from issue #1731 for example. I also tried switching off `--insecure` or `--no-upstream-cert`. I'm currently using those flags because Burp (which I actually intend to use instead of curl) apparently doesn't send SNI [properly](https://support.portswigger.net/customer/portal/questions/16827939-burp-does-not-set-sni-on-the-outgoing-connection-to-an-ssl-enabled-web-server).

##### System information

```
Mitmproxy version: 2.0.2 (1.2.0dev0000-0x8cba0352e)
Python version: 3.6.1
Platform: Darwin-16.5.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Mac version: 10.12.4 ('', '', '') x86_64
```

**Comment by mhils** [comment]
Thanks for the fantastic bug report! 😃 

This seems to be a bug. Here is the socat output on master with another mitmproxy instance running on port 999:
```
mitmproxy -p 8081 -s uplink.py --mode upstream:http://localhost:8082 --ssl-insecure --set upstream_cert=false
```
```
> 2017/05/11 13:12:03.064050  length=119 from=0 to=118
CONNECT www.google.com:80 HTTP/1.1\r
Host: www.google.com:443\r
User-Agent: curl/7.47.0\r
Proxy-Connection: Keep-Alive\r
\r
< 2017/05/11 13:12:03.120659  length=39 from=0 to=38
HTTP/1.1 200 Connection established\r
\r
> 2017/05/11 13:12:03.426827  length=239 from=119 to=357
...........2...?6n.dm*w`]..qm.{.|.u...q..]<..B.+.,.	.#.
.$.\b./.0...'...(......./.<.5.=.A...
.....3.g.9.k.E.........{.........www.google.com.\v.......
<snip>
socat[1498] E write(6, 0x15294a0, 31): Broken pipe


> 2017/05/11 13:12:03.762322  length=115 from=0 to=114
CONNECT www.google.com:80 HTTP/1.1\r
Host: www.google.com\r
User-Agent: curl/7.47.0\r
Proxy-Connection: Keep-Alive\r
\r
< 2017/05/11 13:12:03.846242  length=39 from=0 to=38
HTTP/1.1 200 Connection established\r
\r
> 2017/05/11 13:12:03.849285  length=78 from=115 to=192
GET / HTTP/1.1\r
Host: www.google.com\r
User-Agent: curl/7.47.0\r
Accept: */*\r
\r
< 2017/05/11 13:12:03.988207  length=243 from=39 to=281
HTTP/1.1 302 Found\r
Cache-Control: private\r
Content-Type: text/html; charset=UTF-8\r
Referrer-Policy: no-referrer\r
Location: http://www.google.de/?gfe_rd=cr&ei=BUcUWc-SFMOK8QeV-IXgBg\r
Content-Length: 258\r
Date: Thu, 11 May 2017 11:12:05 GMT\r
\r
< 2017/05/11 13:12:04.000173  length=258 from=282 to=539
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.de/?gfe_rd=cr&amp;ei=BUcUWc-SFMOK8QeV-IXgBg">here</A>.\r
</BODY></HTML>\r
```

This looks like we initially establish a TLS connection, but then immediately disconnect and open a new (plaintext) connection. Looking at the code, we always establish a connection [here](https://github.com/mitmproxy/mitmproxy/blob/6af72160bf98b58682b8f9fc5aabf51928d2b1d3/mitmproxy/proxy/protocol/http.py#L220). I'm not exactly sure why that is the case, maybe we just need to call `self.set_server(address)` at this point. 

@Kriechi @ujjwal96: Can one of you verify if that works? I'm moving this weekend, so I won't get to this before the end of next week.

**Comment by icese7en** [comment]
Need this feature either.

Like the post I send:

**Comment by felixgr** [comment]
The issue @icese7en linked to is the same I'm having.

**Comment by mhils** [comment]
@felixgr @icese7en: Sorry that this took so long! I just pushed #2367, which should fix this issue. Does that work for you two?

**Comment by felixgr** [comment]
No problem at all. Thanks! Works like a charm!

New command line
`mitmproxy -p 8081 -s uplink.py -m upstream:http://localhost:8082 -k`

**Comment by icese7en** [comment]
Client <- HTTPS -> mitmproxy Proxy <- HTTP -> B Proxy (Like charles)

B Proxy still get connect request from mitmproxy.

The inline script I use:

```
from mitmproxy import ctx


def http_connect(flow):
    flow.request.scheme = 'http'
    flow.request.port = 80
    ctx.log.info('script: connect ' + repr(flow))


def request(flow):
    flow.request.scheme = 'http'
    flow.request.port = 80
    ctx.log.info('script: request ' + repr(flow))
```

And the command line I use:

```
mitmdump -p 5678 -s uplink.py -m upstream:http://localhost:8989
```

Then charles get connect request from mitmproxy:

```
CONNECT www.google.com:80 HTTP/1.1
Host: www.google.com:443
User-Agent: curl/7.43.0
Proxy-Connection: Keep-Alive
```

Even if I use the snippet from #2367 `RewriteToHttp`, Charles still get connect request but http port is 443 now `CONNECT www.google.com:443 HTTP/1.1`.

**Comment by mhils** [comment]
Thank you two for the quick feedback! :)

@icese7en: There's still a CONNECT request, but no TLS negotiation after that. I was looking at what it would take to remove the CONNECT as well, but that's not easily doable with our current infrastructure - sorry.

**Comment by pansila** [comment]
I'm using the mitmproxy 6.0.2 and this seems doesn't work, mitmproxy is still sending tls handshake to the upstream proxy.

https2http.py:
```
#!/usr/bin/env python3

from mitmproxy import ctx

class https2http:
        def http_connect(self, flow):
                flow.request.scheme = 'http'
                #flow.request.port = 1088
                ctx.log.info('script: connect '+repr(flow))

        def request(self, flow):
                flow.request.scheme = 'http'
                #flow.request.port = 1088
                ctx.log.info('script: request '+repr(flow))

addons = [https2http()]
```

mitmproxy events:
```
info: Loading script https2http.py
info: 172.17.64.1:63197: clientconnect
info: script: connect <HTTPFlow?
  request = Request(CONNECT www.bing.com:443)?
  client_conn = <ClientConnection: [TLSv1.3] [ALPN: http/1.1] 172.17.64.1:63197>?
  server_conn = <ServerConnection: 127.0.0.1:1088>>
warn: 172.17.64.1:63197: Cannot establish TLS with 127.0.0.1:1088 (sni: None): TlsException("SSL handshake error:
SysCallError(-1, 'Unexpected EOF')")
info: 172.17.64.1:63197: clientdisconnect
```

command
```
mitmproxy --mode upstream:http://127.0.0.1:1088 --ssl-insecure --set upstream_cert=false --certs=~/workspace/custom_certs/server.pem -s https2http.py
```
