### ISSUE TITLE
Unable to run mitmweb [5.0/5.0.1]

### ISSUE THREAD

**Issue by imsaion** [mitmproxy/mitmproxy#3804]
#### Problem Description

Trying to run:

**D:\...\mitmproxy-5.0.1-windows>mitmweb.exe**

And what happens:

Traceback (most recent call last):
  File "mitmweb", line 2, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\tools\main.py", line 22, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\tools\_main.py", line 14, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\master.py", line 7, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\addonmanager.py", line 8, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\eventsequence.py", line 5, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\http.py", line 7, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\net\http\__init__.py", line 1, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\net\http\request.py", line 11, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\net\http\message.py", line 5, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\net\http\encoding.py", line 11, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\brotli.py", line 8, in <module>
ImportError: DLL load failed [...]
[xxxx] Failed to execute script mitmweb

**Comment by mhils** [comment]
The 5.0.1 binaries work just fine for me. Which Windows version are you running this on?

**Comment by imsaion** [comment]
10.0.17763.253 (Win10 RS5 [1809] October 2018 Update) (64-bit)

**4.0.4 is working like a charm [mitmweb --version]:**
Mitmproxy: 4.0.2 binary
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Windows-10-10.0.17763

**Comment by mhils** [comment]
Thanks you two for reporting this. I unfortunately can't reproduce it. Could you try the following?

1. Clear %TEMP% 
2. Run mitmweb (and let it crash)
3. Verify that this created a _MEI XXXX folder.
4. Now check if there are any files that have "brotli" in their name in that folder. Are there any?

Alternatively, run [procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) and figure out which DLL we're trying to load that's not there.

**Comment by imsaion** [comment]
Strange!
I've just fetched **mitmproxy-5.0.1-windows.zip** [**CRC: CEE87477**] from the site and it runs OK now. :-O

mitmproxy-5.0.1-windows>mitmweb.exe --version
Mitmproxy: 5.0.1 binary
Python:    3.7.5
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Windows-10-10.0.17763-SP0

**Comment by imsaion** [comment]
Sorry! Wrong button! 

Strange!
I've just fetched **mitmproxy-5.0.1-windows.zip** [**CRC: CEE87477**] from the site and it runs OK now. :-O

mitmproxy-5.0.1-windows>mitmweb.exe --version
Mitmproxy: 5.0.1 binary
Python:    3.7.5
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Windows-10-10.0.17763-SP0

**Comment by piortest** [comment]
The problem persists on Windows Server 2019 Datacenter (version 1809, build 17763.1039).

**Comment by imsaion** [comment]
I'm not sure but I may have had my %TEMP% directory cleared in a meantime, so it could have helped. :-?

**Comment by mhils** [comment]
If you encounter this, please follow the instructions in https://github.com/mitmproxy/mitmproxy/issues/3804#issuecomment-589864833. We need more details to track this down.

**Comment by anadius** [comment]
+1 for procmon. For me it was `MSVCP140.dll` and `api-ms-win-appmodel-runtime-l1-1-2.DLL`, so VC Redist 2015-2019 was missing. After installing it everything works fine.

**Comment by techathena** [comment]
Hey, I found that transparent mode is not officially supported on windows . @mhils has answered something similar here.
https://github.com/mitmproxy/mitmproxy/issues/335#issuecomment-53438757
Hope it helps @anadius

**Comment by Gowee** [comment]
@mhils I can reproduce this problem in a Windows Sandbox of which the host is ver 1903. I am trying to follow [your instructions](https://github.com/mitmproxy/mitmproxy/issues/3804#issuecomment-589864833). But there is neither something like `_MEI` nor `brotli` in `%temp%`(`AppData\Local\temp`). I have no idea how to use `procmon` to locate the problem. Could you please give some further instructions?

**Comment by Kriechi** [comment]
We released mitmproxy v5.1.0 - please try the latest binaries.

**Comment by Gowee** [comment]
@Kriechi 

Hi.

It seems that the problem still persists.

Manually installing [this](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) is inevitable even for the new [5.1.1 Windows installer](https://snapshots.mitmproxy.org/5.1.1/mitmproxy-5.1.1-windows-installer.exe).

**Comment by mhils** [comment]
Thanks - looks like this issue was introduced when moving CI to GitHub Actions, where the Windows SDK isn't available on workers by default.

Can someone please confirm that the binaries at https://snapshots.mitmproxy.org/branches/ucrt/ fix the problem and run fine without installing VC Redist?

**Comment by Gowee** [comment]
```
...
ImportError: DLL load failed: The specified module could not be found.
[1052] Failed to execute script mitmdump 
```


```
Mitmproxy: 6.0.0.dev binary                                                                                             Python:    3.7.6                                                                                                        OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020                                                                                  Platform:  Windows-10-10.0.18362-SP0

**Comment by Frutuoso14** [comment]
Hi, I am trying to run MITMPROXY on Ubuntu 18.04 on windows 10 virtual machine. 
I already did the installation but I always get this when I launch it:
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 11, in <module>
    sys.exit(mitmproxy())
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/tools/_main.py", line 146, in mitmproxy
    from mitmproxy.tools import console
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/tools/console/__init__.py", line 1, in <module>
    from mitmproxy.tools.console import master
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/tools/console/master.py", line 17, in <module>
    from mitmproxy import addons
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/addons/__init__.py", line 13, in <module>
    from mitmproxy.addons import proxyauth
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/addons/proxyauth.py", line 3, in <module>
    import ldap3
  File "/usr/local/lib/python3.6/dist-packages/ldap3/__init__.py", line 139, in <module>
    from .core.connection import Connection
  File "/usr/local/lib/python3.6/dist-packages/ldap3/core/connection.py", line 44, in <module>
    from ..operation.compare import compare_operation, compare_request_to_dict
  File "/usr/local/lib/python3.6/dist-packages/ldap3/operation/compare.py", line 28, in <module>
    from ..operation.search import ava_to_dict
  File "/usr/local/lib/python3.6/dist-packages/ldap3/operation/search.py", line 41, in <module>
    from pyasn1.error import PyAsn1UnicodeDecodeError
ImportError: cannot import name 'PyAsn1UnicodeDecodeError'

Anybody knows hot fix this or can someone explain me how to install mitmproxy via Binary Packages?

**Comment by mhils** [comment]
@Gowee: Thanks! I have updated the ucrt binaries again, could you check if https://snapshots.mitmproxy.org/branches/ucrt/mitmproxy-ucrt-windows.zip works for you?

**Comment by Gowee** [comment]
@mhils Thanks for your effort. I am afraid that the problem remains the same there (still requiring VC Redist).
But in case it is specific to my machine, it would be good if someone else can have a second check.

**Comment by The-Kurd** [comment]
I can confirm this problem on two diffrent fresh Windows 10 machines with Version 5.1. Using 4.0.4 however works….

Let me know if any testing is needed.

**Comment by hassoon3** [comment]
Just install vc_redist.x64.exe or vc_redist.x86.exe and try again.

**Comment by hash3liZer** [comment]
@hassoon3 Did that work for you?
