### ISSUE TITLE
[Window] User can't open mitmweb.exe in bin folder

### ISSUE THREAD

**Issue by hieuTranEnouvo** [mitmproxy/mitmproxy#3932]
#### Steps to reproduce the behavior:
1. Install mitmproxy on win 10 64 bit
2. Go to the "bin" folder in C disk 
3. Clicking on mitmweb.exe (run administrator)

#### System Information
"mitmproxy --version": 5.0

**Comment by Kriechi** [comment]
How did you install it?
Where and what did you download?
We just released v5.1 this morning - please try with the most recent version.
What happens after you click on mitmweb.exe? Is there an error message?

**Comment by hieuTranEnouvo** [comment]
I just download v5.1 which still can't open mitmweb.exe
pls see the video
https://youtu.be/JOJNzzUeaFE
I can not get log for you

**Comment by hieuTranEnouvo** [comment]
> How did you install it?
> Where and what did you download?
> We just released v5.1 this morning - please try with the most recent version.
> What happens after you click on mitmweb.exe? Is there an error message?

I just download v5.1 which still can't open mitmweb.exe
pls see the video
https://youtu.be/JOJNzzUeaFE
I can not get log for you @Kriechi

**Comment by Shnitzelil** [comment]
I got the same one.
Version 5.1.1 on Windows 10

**Comment by mhils** [comment]
Hm, the binaries work fine for me. Screenshot from the video:

![image](https://user-images.githubusercontent.com/1019198/79563764-b0ac4980-80ad-11ea-9107-da00570f7762.png)

@Shnitzelil: Can you please open a command line prompt, run "mitmweb.exe" from there and see if you have the same output?

Also, which Windows 10 version are you two on? 1909 or 2004? https://support.microsoft.com/en-us/help/13443/windows-which-version-am-i-running

**Comment by mhils** [comment]
Also, since you have since opened other issues: How did you fix it?

**Comment by Shnitzelil** [comment]
> Also, since you have since opened other issues: How did you fix it?

The mitmdump working ok... the issue here is with mitmweb.

**Comment by Shnitzelil** [comment]
> Hm, the binaries work fine for me. Screenshot from the video:
> 
> ![image](https://user-images.githubusercontent.com/1019198/79563764-b0ac4980-80ad-11ea-9107-da00570f7762.png)
> 
> @Shnitzelil: Can you please open a command line prompt, run "mitmweb.exe" from there and see if you have the same output?
> 
> Also, which Windows 10 version are you two on? 1909 or 2004? https://support.microsoft.com/en-us/help/13443/windows-which-version-am-i-running

I'm working with 1909

And I downloaded the files from [here](https://snapshots.mitmproxy.org/5.1.1/mitmproxy-5.1.1-windows.zip)

The output I see is

Traceback (most recent call last):
  File "mitmweb", line 4, in <module>
  File "mitmproxy\tools\_main.py", line 171, in mitmweb
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\tools\web\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\tools\web\master.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\site-packages\tornado\httpserver.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\site-packages\tornado\http1connection.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\site-packages\tornado\iostream.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\site-packages\tornado\netutil.py", line 39, in <module>
  File "ssl.py", line 589, in create_default_context
  File "ssl.py", line 490, in load_default_certs
  File "ssl.py", line 482, in _load_windows_store_certs
ssl.SSLError: nested asn1 error (_ssl.c:4003)
[12184] Failed to execute script mitmweb

**Comment by mhils** [comment]
@Shnitzelil: This looks like you have an invalid CA certificate installed on your system. See https://bugs.python.org/issue35665 for details.
