### ISSUE TITLE
Ignoring server verification error, continuing with connection

### ISSUE THREAD

**Issue by adbqpa** [mitmproxy/mitmproxy#4252]
#### Problem Description
Warn: ::1:52204: Ignoring server verification error, continuing with connectionTraceback (most recent call last):
  File "mitmproxy/proxy/server.py", line 121, in handle
  File "mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
  File "mitmproxy/proxy/protocol/tls.py", line 285, in __call__
  File "mitmproxy/proxy/protocol/http1.py", line 83, in __call__
  File "mitmproxy/proxy/protocol/http.py", line 188, in __call__
  File "mitmproxy/proxy/protocol/http.py", line 260, in _process_flow
  File "mitmproxy/proxy/protocol/http.py", line 206, in handle_regular_connect
  File "mitmproxy/proxy/protocol/tls.py", line 278, in __call__
  File "mitmproxy/proxy/protocol/tls.py", line 368, in _establish_tls_with_client_and_server
  File "mitmproxy/proxy/protocol/tls.py", line 372, in _establish_tls_with_client
  File "mitmproxy/proxy/protocol/tls.py", line 508, in _find_cert
  File "mitmproxy/certs.py", line 356, in get_cert
  File "mitmproxy/certs.py", line 112, in dummy_cert
  File "site-packages/OpenSSL/crypto.py", line 585, in __setattr__
  File "site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
OpenSSL.crypto.Error: [('asn1 encoding routines', 'ASN1_mbstring_ncopy', 'string too long')]

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy

#### Steps to reproduce the behavior:
1. Start mitmproxy with option --ssl-insecure
2. Setup browser to using mitmproxy
3. Try to open https://goszakup.gov.kz/

#### System Information
Mitmproxy: 5.0.1 binary
Python:    3.7.5
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Darwin-19.6.0-x86_64-i386-64bit

**Comment by Prinzhorn** [comment]
The certificate organization is

```
РЕСПУБЛИКАНСКОЕ ГОСУДАРСТВЕННОЕ УЧРЕЖДЕНИЕ \"МИНИСТЕРСТВО ФИНАНСОВ РЕСПУБЛИКИ КАЗАХСТАН\"
```

or 

```
b'\xd0\xa0\xd0\x95\xd0\xa1\xd0\x9f\xd0\xa3\xd0\x91\xd0\x9b\xd0\x98\xd0\x9a\xd0\x90\xd0\x9d\xd0\xa1\xd0\x9a\xd0\x9e\xd0\x95 \xd0\x93\xd0\x9e\xd0\xa1\xd0\xa3\xd0\x94\xd0\x90\xd0\xa0\xd0\xa1\xd0\xa2\xd0\x92\xd0\x95\xd0\x9d\xd0\x9d\xd0\x9e\xd0\x95 \xd0\xa3\xd0\xa7\xd0\xa0\xd0\x95\xd0\x96\xd0\x94\xd0\x95\xd0\x9d\xd0\x98\xd0\x95 "\xd0\x9c\xd0\x98\xd0\x9d\xd0\x98\xd0\xa1\xd0\xa2\xd0\x95\xd0\xa0\xd0\xa1\xd0\xa2\xd0\x92\xd0\x9e \xd0\xa4\xd0\x98\xd0\x9d\xd0\x90\xd0\x9d\xd0\xa1\xd0\x9e\xd0\x92 \xd0\xa0\xd0\x95\xd0\xa1\xd0\x9f\xd0\xa3\xd0\x91\xd0\x9b\xd0\x98\xd0\x9a\xd0\x98 \xd0\x9a\xd0\x90\xd0\x97\xd0\x90\xd0\xa5\xd0\xa1\xd0\xa2\xd0\x90\xd0\x9d"'
```

This is about where my knowledge ends. I don't know what the max length is or if the characters are the issue and not length.

So basically I'm not sure if this is a mitmpoxy issue or not.

**Comment by mhils** [comment]
Thanks for the triage @Prinzhorn! Pretty much this was fixed by https://github.com/mitmproxy/mitmproxy/commit/cff5b820a6de780411be5fadc057af012de11774, please update to the latest mitmproxy release.

**Comment by Prinzhorn** [comment]
@mhils I'm sorry I wasn't clear enough. I tested on master and like I said the problem is the `organization`, not `commonname`. Crash happens here https://github.com/mitmproxy/mitmproxy/blob/34a284bf4af226c56bffc1b2d3de15f4eaf90f57/mitmproxy/certs.py#L115

**Comment by adbqpa** [comment]
> Thanks for the triage @Prinzhorn! Pretty sure this was fixed by [cff5b82](https://github.com/mitmproxy/mitmproxy/commit/cff5b820a6de780411be5fadc057af012de11774), please update to the latest mitmproxy release.

version 5.3.0 still crashes

Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/proxy/protocol/tls.py", line 285, in __call__
    layer()
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/proxy/protocol/http1.py", line 100, in __call__
    layer()
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/proxy/protocol/http.py", line 203, in __call__
    if not self._process_flow(flow):
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/proxy/protocol/http.py", line 276, in _process_flow
    return self.handle_regular_connect(f)
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/proxy/protocol/http.py", line 221, in handle_regular_connect
    layer()
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/proxy/protocol/tls.py", line 278, in __call__
    self._establish_tls_with_client_and_server()
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/proxy/protocol/tls.py", line 368, in _establish_tls_with_client_and_server
    self._establish_tls_with_client()
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/proxy/protocol/tls.py", line 372, in _establish_tls_with_client
    cert, key, chain_file = self._find_cert()
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/proxy/protocol/tls.py", line 508, in _find_cert
    return self.config.certstore.get_cert(host, list(sans), organization)
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/certs.py", line 360, in get_cert
    cert=dummy_cert(
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/mitmproxy/certs.py", line 115, in dummy_cert
    cert.get_subject().O = organization
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/OpenSSL/crypto.py", line 577, in __setattr__
    _raise_current_error()
  File "/usr/local/Cellar/mitmproxy/5.3.0/libexec/lib/python3.9/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: [('asn1 encoding routines', 'ASN1_mbstring_ncopy', 'string too long')]

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy

**Comment by jaykijay** [comment]
I have some similar error:

`::ffff:10.42.0.240:40016: Ignoring server verification error, continuing with connection
Traceback (most recent call last):
  File "mitmproxy/proxy/server.py", line 121, in handle
  File "mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
  File "mitmproxy/proxy/protocol/tls.py", line 278, in __call__
  File "mitmproxy/proxy/protocol/tls.py", line 368, in _establish_tls_with_client_and_server
  File "mitmproxy/proxy/protocol/tls.py", line 372, in _establish_tls_with_client
  File "mitmproxy/proxy/protocol/tls.py", line 508, in _find_cert
  File "mitmproxy/certs.py", line 365, in get_cert
  File "mitmproxy/certs.py", line 124, in dummy_cert
  File "OpenSSL/crypto.py", line 764, in __init__
  File "OpenSSL/_util.py", line 54, in exception_from_error_queue
OpenSSL.crypto.Error: [('X509 V3 routines', 'v2i_GENERAL_NAME_ex', 'missing value'), ('X509 V3 routines', 'X509V3_EXT_nconf', 'error in extension')]

10.42.0.240:40016: Traceback (most recent call last):
  File "mitmproxy/proxy/server.py", line 121, in handle
  File "mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
  File "mitmproxy/proxy/protocol/tls.py", line 278, in __call__
  File "mitmproxy/proxy/protocol/tls.py", line 368, in _establish_tls_with_client_and_server
  File "mitmproxy/proxy/protocol/tls.py", line 372, in _establish_tls_with_client
  File "mitmproxy/proxy/protocol/tls.py", line 508, in _find_cert
  File "mitmproxy/certs.py", line 365, in get_cert
  File "mitmproxy/certs.py", line 124, in dummy_cert
  File "OpenSSL/crypto.py", line 764, in __init__
  File "OpenSSL/_util.py", line 54, in exception_from_error_queue
OpenSSL.crypto.Error: [('X509 V3 routines', 'v2i_GENERAL_NAME_ex', 'missing value'), ('X509 V3 routines', 'X509V3_EXT_nconf', 'error in extension')]`
