### ISSUE TITLE
All HTTP/2 requests are streamed if proxy is started with --set stream_large_bodies - "content missing"

### ISSUE THREAD

**Issue by KORraNpl** [mitmproxy/mitmproxy#4470]
#### Problem Description
As in the title - I noticed that I cannot view content of responses in some cases, because there is "[content missing]". After a bit of digging, it seems that setting `stream_large_bodies` triggers the issue - even if response is way below the threshold.

#### Steps to reproduce the behavior:
1. Start mitmproxy: `mitmproxy --set stream_large_bodies=10m` - 10 MB threshold
2. Make an HTTP/2 request, i.e. `curl -x 127.0.0.1:8080 -L https://www.google.com 1>/dev/null`
3. Check request in mitmproxy - `[content missing]` despite response size is way below threshold - 14438 bytes.
4. Events:
```
info: 127.0.0.1:59143: clientconnect
info: Streaming response from www.google.com
info: 127.0.0.1:59143: clientdisconnect
```

#### System Information
```
Mitmproxy: 6.0.2
Python:    3.9.2
OpenSSL:   OpenSSL 1.1.1j  16 Feb 2021
Platform:  macOS-11.2.1-x86_64-i386-64bit
```

Requests HTTP/1.1 seems to be not affected. Also, I can't reproduce it on Ubuntu running via WSL1. Could be related to #4291.

**Comment by Prinzhorn** [comment]
I can reproduce this with 6.0.2 and also with the latest master.

**Comment by Prinzhorn** [comment]
This returns -1

https://github.com/mitmproxy/mitmproxy/blob/4bd7b6c4eadeaca712f63e0e73f20bcf6aadbffb/mitmproxy/addons/streambodies.py#L34-L36

I'm not too familiar with the code but I'll look into it. Since the package is explicitly called `http1` I wonder if it works with http2 or if it's just a helper in the wrong package.

**Comment by Prinzhorn** [comment]
Neat, so it looks like the `stream_large_bodies` addon has always been broken, but with HTTP/2 it has become way more common to omit the `content-length` header. I think I've fixed it.

**Comment by KORraNpl** [comment]
@Prinzhorn Good catch! Seems like `content-length` is [optional in HTTP/2](https://bz.apache.org/bugzilla/show_bug.cgi?id=63009), but also in older versions. But the weird thing is:
`curl -x 127.0.0.1:8080 -L https://www.google.com --http1.1 1>/dev/null`
does not return `content-length` too, but the response is not streamed by mitmproxy.

**Comment by Prinzhorn** [comment]
It's using `Transfer-Encoding:  chunked`, this case is already handled https://github.com/mitmproxy/mitmproxy/blob/4bd7b6c4eadeaca712f63e0e73f20bcf6aadbffb/mitmproxy/net/http/http1/read.py#L78-L79

Well, this should be 0 tho I guess :thinking:

**Comment by mhils** [comment]
@Prinzhorn: 

https://github.com/mitmproxy/mitmproxy/blob/4bd7b6c4eadeaca712f63e0e73f20bcf6aadbffb/mitmproxy/net/http/http1/read.py#L50-L54

I'm on the run, but here are my TL;DR thoughts:

 - streaming if unknown annoys some people (see this issue)
 - not streaming if unknown often breaks the whole purpose of streaming (live video is more often than not chunked)

What we could do instead: Check [here](https://github.com/mitmproxy/mitmproxy/blob/4bd7b6c4eadeaca712f63e0e73f20bcf6aadbffb/mitmproxy/proxy/layers/http/__init__.py#L239) if we exceeded max_body_size, and start streaming if so.

**Comment by r00t-** [comment]
i'm also opposed to mitmproxy ever dynamically _not_ logging data while it's in use - it should not lose data unexpectedly.
i would suggest to reject/cancel requests if they are/become too large, that leaves the user with a warning at least.
i actually tried to patch this in before, but with little luck due to lacking python skills. maybe i'll try again, thanks for the pointer into the code.

**Comment by Prinzhorn** [comment]
> it should not lose data unexpectedly.

I'm in the same boat regarding that. I don't want data to get lost unexpectedly.

>    not streaming if unknown often breaks the whole purpose of streaming (live video is more often than not chunked)

Maybe streaming chunked responses could be a separate option/addon `stream_chunked_responses`? But I guess this depends entirely on the use-case and people can always write their own two line addon to enable streaming for chunked responses.

> What we could do instead: Check [here](https://github.com/mitmproxy/mitmproxy/blob/4bd7b6c4eadeaca712f63e0e73f20bcf6aadbffb/mitmproxy/proxy/layers/http/__init__.py#L239) if we exceeded max_body_size, and start streaming if so.

That sounds reasonable. Is this something that could theoretically be exposed to addons or would `stream_large_bodies` then need to be moved into the core? In either case we only need to look at `request_body_buf` size if `content-length` is missing.

**Comment by mhils** [comment]
> That sounds reasonable. Is this something that could theoretically be exposed to addons or would stream_large_bodies then need to be moved into the core?

This would mean we'd move it to the core, but that's ok - there is lots of streaming logic in the proxy core anyways, the option isn't adding much here. :-) I'd be happy to accept a PR! 😃 Here's a rough description of what needs to be done:

1. Move [the option definition](https://github.com/mitmproxy/mitmproxy/blob/42a1345daf015b345f29e976434c29f4c84175df/mitmproxy/addons/streambodies.py#L13-L28) into `addons/proxyserver.py`. We should keep the validation done by `configure` around, which makes mitmproxy not accept invalid values for `stream_large_bodies`. But we don't need to have a max_size property on the Proxyserver addon. Calling `human.parse_size` on demand is very cheap as it's cached.
2. `rm addons/streambodies.py` (and remove reference in `addons/__init__.py`)
3. Replicate existing functionality: Set the `stream` request property based on `stream_large_bodies` [here](https://github.com/mitmproxy/mitmproxy/blob/42a1345daf015b345f29e976434c29f4c84175df/mitmproxy/proxy/layers/http/__init__.py#L191), treat an unknown content length as "don't stream".
4. Add the funcionality to start streaming chunked data once we exceed a certain size: Check [here](https://github.com/mitmproxy/mitmproxy/blob/42a1345daf015b345f29e976434c29f4c84175df/mitmproxy/proxy/layers/http/__init__.py#L239) if `request_body_buf > stream_large_bodies`. If so, switch to streaming by calling `start_request_stream` and transmitting the existing buffer.
5. Write tests. See [here](https://github.com/mitmproxy/mitmproxy/blob/93de96a720a60365117ef41f0801e8cff7ac06bd/test/mitmproxy/proxy/layers/http/test_http.py#L269-L295) for a similar test. You can set options in tests [like this](https://github.com/mitmproxy/mitmproxy/blob/93de96a720a60365117ef41f0801e8cff7ac06bd/test/mitmproxy/proxy/layers/http/test_http.py#L238).
6. Submit a PR for feedback.
7. Repeat 4-5 for responses streaming. 🚀 

As always, don't hesistate to reach out if you are stuck somewhere 😃

**Comment by mhils** [comment]
I've just fixed this, thanks again! For `Transfer-Encoding: chunked` requests without `Content-Length` header, mitmproxy now buffers the message until the `stream_large_bodies` limit is hit, at which point it will transition to streaming. I think this is the best compromise we can make for message bodies of unknown length. 😃

**Comment by KORraNpl** [comment]
@mhils Yup, I can confirm it works in my case, thanks for addressing this! :) I will continue using snapshots and keep an eye on any issues.

**Comment by zarni0** [comment]
I am still getting this error
even though i set a limit of 999999999999
"response content missing"
Any ideas?

**Comment by mhils** [comment]
@zarni0: make sure that you are using the latest mitmproxy release, otherwise please open an new issue with easy steps to reproduce it.
