### ISSUE TITLE
mithproxyweb - Uncaught TypeError: Cannot read property 'scheme' of undefined

### ISSUE THREAD

**Issue by marcelrv** [mitmproxy/mitmproxy#4581]
#### Problem Description
Using mithproxyweb
Screen get lost (blank) when using the `rawtcp` and such a packet is arriving.
In the browser console the the following error is displayed

```
Uncaught TypeError: Cannot read property 'scheme' of undefined
    at TLSColumn (app.js:50)
    at beginWork (vendor.js:122)
    at o (vendor.js:122)
    at u (vendor.js:122)
    at c (vendor.js:122)
    at batchedUpdates (vendor.js:122)
    at qb (vendor.js:122)
    at ob (vendor.js:122)
    at Object.batchedUpdates (vendor.js:122)
    at dispatchEvent (vendor.js:122
```

note, reloading the screen will resolve it, but when scrolling down to the screen disaprears again (total white browser screen)
Don't know if relevant, or even if that is causing this, but I was trying to look at a MQTT protocol with TLS

#### Steps to reproduce the behavior:
1.  enable `rawtcp` (I did it in the through mithproxy web interface)
2.  have a non http packet arrive (screen is fine until the packet is loaded)

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 6.0.2
Python:    3.8.5
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.4.0-72-generic-x86_64-with

**Comment by gregd72002** [comment]
Same problem here on OSX when capturing rawtcp or opening previously captured rawtcp flow

```
vendor.js:122 TypeError: Cannot read property 'scheme' of undefined
    at TLSColumn (app.js:50)
    at beginWork (vendor.js:122)
    at o (vendor.js:122)
    at u (vendor.js:122)
    at c (vendor.js:122)
    at f (vendor.js:122)
    at p (vendor.js:122)
    at Object.enqueueSetState (vendor.js:122)
    at i.v.setState (vendor.js:167)
    at i.onStateChange (vendor.js:128)
```

Output of "mitmweb --version":
```
➜  mitmweb --version  
Mitmproxy: 6.0.2
Python:    3.9.4
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  macOS-10.15.7-x86_64-i386-64bit
```

**Comment by kamikazechaser** [comment]
Getting the same error on Brave:

```
Mitmproxy: 7.0.2 binary
Python:    3.9.5
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  Linux-5.10.52-antix.1-amd64-smp-x86_64-with-glibc2.28
```

and the following on Firefox:

```
Uncaught TypeError: t.request is undefined (app.js 50:177)
# This is the catch block
```

Similar behavior. On opening the page, it redirects to a blank `http://localhost:8002/#/flows` page almost immediately.

**Comment by mhils** [comment]
I just added basic TCP support today, this should be fixed with #4779 tomorrow. :)

**Comment by mhils** [comment]
This is resolved on the latest development snapshots now and will work in the next release. :)

**Comment by jab** [comment]
Great this will be fixed in the next release! <3  Is there a workaround for this in the meantime?

**Comment by mhils** [comment]
You can use the development snapshots from https://mitmproxy.org/downloads :)

**Comment by aejii** [comment]
error still appears, I was following https://docs.mitmproxy.org/stable/howto-install-system-trusted-ca-android/ and it's appears after the last `adb reboot` 

```
mitmweb.exe --version
Mitmproxy: 7.0.4 binary
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Windows-10-10.0.22000-SP0
```

```
vendor.js:122 TypeError: Cannot read properties of undefined (reading 'scheme')
    at TLSColumn (app.js:50)
    at beginWork (vendor.js:122)
    at o (vendor.js:122)
    at u (vendor.js:122)
    at c (vendor.js:122)
    at f (vendor.js:122)
    at p (vendor.js:122)
    at Object.enqueueSetState (vendor.js:122)
    at i.v.setState (vendor.js:167)
    at i.onStateChange (vendor.js:128)
```
and
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'scheme')
    at TLSColumn (app.js:50)
    at beginWork (vendor.js:122)
    at o (vendor.js:122)
    at u (vendor.js:122)
    at c (vendor.js:122)
    at f (vendor.js:122)
    at p (vendor.js:122)
    at Object.enqueueSetState (vendor.js:122)
    at i.v.setState (vendor.js:167)
    at i.onStateChange (vendor.js:128)
```

**Comment by mhils** [comment]
This should be fixed if you use the development snapshots (not yet in a release) from https://mitmproxy.org/downloads/#branches/main/.

**Comment by AhmedAbouelkher** [comment]
> This should be fixed if you use the development snapshots (not yet in a release) from [mitmproxy.org/downloads/#branches/main](https://mitmproxy.org/downloads/#branches/main/).

Unfortunately, the issue still exists in `8.0.0.dev` and the issue is random, sometimes it works fine and other times not.

This exception is thrown in the console and the web page is completely blank.

```
app.js:1 Uncaught Error: Cannot find module 'react'
    at s (app.js:1)
    at app.js:1
    at Object.1../backends/static (app.js:2)
    at s (app.js:1)
    at e (app.js:1)
    at app.js:1
```

Specs:
```
Mitmproxy: 8.0.0.dev binary
Python:    3.9.9
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  macOS-10.16-x86_64-i386-64bit
```

**Comment by Mattwmaster58** [comment]
I couldn't for the life of me get this to work, I'd shutdown and restart the proxy to no avail - would still get this blank screen message. After grabbing mitmproxy-8.0.0.dev0-py3-none-any.whl everything seems to be working so far
